[package]
name = "advent"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = "0.16.1"
nom = "8.0.0"
num-traits = "0.2.19"
reqwest = { version = "0.12.24", features = ["blocking"] }
thiserror = "1.0.69"
